问卷调查/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/add/$', views.add),
    url(r'^index/$', views.index),
    url(r'^login/$', views.login),
    url(r'^dell/$', views.dell),
    url(r'^$', views.index),
    url(r'^data/(\d+)/$', views.data),
    url(r'^questions/(\d+)/(\d+)/$', views.answer),
    url(r'^questions/(\d+)/$', views.questions),


]

app01/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    """
    员工表
    """
    username = models.CharField(max_length=32,verbose_name="用户名")
    password = models.CharField(max_length=32,verbose_name="密码")

    def __str__(self):
        return self.username


class ClassList(models.Model):
    """
    班级表
    """
    title = models.CharField(max_length=32,verbose_name="班级名")
    num = models.IntegerField(verbose_name="班级人数")

    def __str__(self):
        return self.title


class Student(models.Model):
    name = models.CharField(max_length=32,verbose_name="名字")
    password = models.CharField(max_length=32,verbose_name="密码")
    cls = models.ForeignKey(to=ClassList,verbose_name="所属班级",blank=True)

    def __str__(self):
        return self.name


class SurveyInfo(models.Model):
    """
    问卷表
    """
    title = models.CharField(max_length=32,verbose_name="问卷名")
    cls = models.ForeignKey(to=ClassList,verbose_name="问卷班级",blank=True)
    user = models.ForeignKey(to=User,verbose_name="创建者",blank=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    """
    问题表
    """
    title = models.CharField(max_length=32,verbose_name="问题")
    type_list=(
        (1,"单选"),
        (2,"打分(1~10分)"),
        (3,"建议")
    )
    type=models.IntegerField(choices=type_list,verbose_name="类型")
    surveyInfo=models.ForeignKey(to=SurveyInfo,verbose_name="所属问卷",blank=True)

    def __str__(self):
        return self.name


class Option(models.Model):
    """
    单选题的选项
    """
    name = models.CharField(verbose_name='选项名称',max_length=32)
    score = models.IntegerField(verbose_name='选项对应的分值')
    qs = models.ForeignKey(to=Question)

    def __str__(self):
        return self.name


class Answer(models.Model):
    """
    答案表
    """
    student = models.ForeignKey(to=Student,verbose_name="某个学生",blank=True)
    question = models.ForeignKey(to=Question,verbose_name="某个问题",blank=True)
    option = models.ForeignKey(to="Option", null=True, blank=True)
    score = models.CharField(max_length=32,null=True,verbose_name="分数")
    content = models.TextField(null=True,verbose_name="内容")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")

    def __str__(self):
        return self.content

templates/add.html
{% extends "index.html" %}

{% block content %}
    <form action="/index/add/" method="post" novalidate>
    {% csrf_token %}
        <p><h4>问卷名称：</h4><input type="text" name="surveyInfo"></p>
        <p><h4>班级：</h4><select name="cla">
                        {% for cls in cls_list %}
                            <option value="{{ cls.id }}">{{ cls.title }}</option>
                        {% endfor %}
                            </select></p>
        <p><h4>创作人：</h4><select name="user">
                            {% for user in user_list %}
                                    <option value="{{ user.id }}">{{ user.username }}</option>
                            {% endfor %}
                            </select></p>

        <input type="submit" class="btn btn-success" value="完成">
    </form>
{% endblock %}

templates/answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <style>
        ul{
            list-style: none;
        }
        li{
            display: inline-block;
        }
    </style>
</head>
<body>
<form method="post" novalidate>
    {% csrf_token %}
    {% for foo in form %}
    <p>{{ foo.label  }}</p>
         <p>{{ foo }}{{ foo.errors.0 }}</p>
    {% endfor %}
<p><input type="submit" value="提交"></p>
</form>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/jquery3.2.1.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <script src="/static/jquery.cookie.js"></script>
    <style>
        ul{
            list-style: none;
            padding: 10px;
        }
        li{
            margin-top: 5px;
        }
        .hide{
            display: none;
        }
        .add{
            margin-left: 20px;
        }

    </style>
</head>
<body>

<div class="container">
    <div class="row">
        <div style="width: 100%;height: 50px;background-color: #5bc0de">
            <a href="/"><span style="color: white;font-size: 20px;display: inline-block;margin-top: 10px">平台首页</span></a>
            &nbsp; &nbsp; &nbsp;
            <span style="color: white;font-size: 20px;display: inline-block;margin-top: 10px">资产首页</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div style="border: 1px solid royalblue;height: 500px"></div>
        </div>
        <div class="col-md-9 content">
        {% block content %}
            <a href="/index/add/"><button class="btn btn-success" style="margin-top: 10px">添加</button></a>
            <div class="table-responsive" style="margin-top: 30px">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th class="col-md-1"><input type="checkbox"></th>
                        <th class="col-md-2">调查问卷名称</th>
                        <th class="col-md-2">问卷调查班级</th>
                        <th class="col-md-1">参与人数</th>
                        <th class="col-md-1">问卷选项</th>
                        <th class="col-md-2">调查地址</th>
                        <th class="col-md-1">查看评分</th>
                        <th class="col-md-1">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for surveyinfo in surveyinfo_list %}
                        <tr>
                            <td class="col-md-1"><input type="checkbox"></td>
                            <td class="col-md-2"><a href="">{{ surveyinfo.title }}</a></td>
                            <td class="col-md-2">{{ surveyinfo.cls.title }}</td>
                            <td class="col-md-1">0/{{ surveyinfo.cls.num }}</td>
                            <td class="col-md-1"><a href="/questions/{{ surveyinfo.id }}">编辑问卷</a></td>
                            <td class="col-md-2"><a href="/questions/{{ surveyinfo.id }}/{{ surveyinfo.cls.id }}/">/questions/{{ surveyinfo.id }}/{{ surveyinfo.cls.id }}/</a></td>
                            <td class="col-md-1"><a href="">查看评分</a></td>
                            <td class="col-md-1"><a surveyinfo_id = "{{ surveyinfo.id }}" class="del">删除</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
        </div>
    </div>
</div>

{% block js %}
    <script>
        $(function () {
            $(".del").click(function () {
                $(this).addClass("is_me")
                var surveyinfoId = $(this).attr("surveyinfo_id");
                $.ajax({
                    url:"/dell/",
                    type:"GET",
                    data:{
                        surveyinfoId:surveyinfoId
                    },
                    success:function (data) {
                        if (data){
                            $(".is_me").parent().parent().remove()
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <script src="/static/jquery3.2.1.js"></script>
</head>
<body>
    {% csrf_token %}
    <p>用户名：<input type="text"></p>
    <p>密码：<input type="password"></p>
    <p><input type="submit" value="登陆"></p>


    <script>
        $(function () {
            $(":submit").click(function () {
                $.ajax({
                   url:'/login/',
                    type:'POST',
                    data:{
                       csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                        user:$(":text").val(),
                        password:$(":password").val()
                    },
                    success:function (data) {
                        var login = JSON.parse(data);
                        if (login['log']){
                            location.href="/index/"
                        }
                    }
                })
                    
            })
        })
    </script>
</body>
</html>

templates/que.html
{% extends "index.html" %}
{% block content %}
     <div style="margin-left: 700px;margin-top: 20px;margin-bottom: 10px"><button class="btn btn-success" id="add">添加</button>
        <button class="btn btn-info submit">完成</button>
     </div>
        {% for dict in form %}
            <div class="jumbotron" id="{{ dict.id }}">
                <span class="glyphicon glyphicon-remove pull-right cha" aria-hidden="true"></span>
                <ul >
                    <h4>问题：</h4><li>{{ dict.form.title }}</li>
                    <h4>类型：</h4><li>{{ dict.form.type }} <button class="{{ dict.hide }} add">添加选项</button></li>
                    <ul>
                        {% for op in dict.option %}
                            <li id="{{ op.option_id }}">{{ op.option }}<span class="glyphicon glyphicon-remove cha" aria-hidden="true"></span></li>
                        {% endfor %}
                    </ul>
                </ul>
            </div>
        {% endfor %}
{% endblock content%}

{% block js %}
    <script>
        $(function () {
            //添加问题
            $("#add").click(function () {
                var s='<div class="jumbotron"> <span class="glyphicon glyphicon-remove pull-right cha" aria-hidden="true"></span> <ul> <h4>问题：</h4><li><textarea name="title" cols="60" rows="3" maxlength="32" required="" id="id_title"></textarea></li> <h4>类型：</h4><li><select name="type" required="" id="id_type"> <option value="">---------</option> <option value="1">单选</option> <option value="2">打分(1~10分)</option> <option value="3">建议</option> </select> </li><ul></ul></ul> </div>'
             $(".content").append(s)
            });

            //select变换
            $(".content").on("change","select",function () {
                if ($(this).val()==="1"){
                    var s='<button class="add">添加选项</button>';
                    $(this).parent().append(s)
                }else{
                    $(this).parent().next().empty();
                    $(this).next().remove()
                }
            });

            //增加单选项
            $(".content").on("click",".add",function () {
                var s ='<li><label for="id_name">选项名称:</label><input type="text" name="name" maxlength="32" required="" id="id_name"> <label for="id_score">选项对应的分值:</label><input type="number" name="score" required="" id="id_score"><span class="glyphicon glyphicon-remove cha" aria-hidden="true"></span</li>';
                $(this).parent().next().append(s)
            });

            //删除问题
            $(".content").on("click",".cha",function () {
                $(this).parent().remove()
            });

            //提交数据
            $(".submit").click(function () {
                //处理数据
                var data_list = [];
                $(".jumbotron").each(function (i,v) {
                    var dict={};
                    var postion_id = $(v).attr("id");
                    if (postion_id){
                         dict['id'] = postion_id;
                    }
                    var postion_title = $(v).children("ul").children("li").children("textarea").val();
                    dict['postion_title'] = postion_title;
                    var type = $(v).children("ul").children("li").children("select").val();
                    if (type==="1"){
                        var op_l=[];
                        $(v).children("ul").children("ul").children("li").each(function (j,k) {
                            op_dict={};
                            var op_id = $(k).attr("id");
                            op_dict['op_id']=op_id;
                            var op_title = $(k).children(":text").val();
                            op_dict['op_title']=op_title
                            var op_score = $(k).children("#id_score").val();
                            op_dict['op_score']=op_score;
                            op_l.push(op_dict)
                        })
                    }
                    dict['type']= type;
                    dict['option']=op_l;
                    data_list.push(dict)
                });
               $.ajax({
                   url:"/data/{{ nid }}/",
                   type:"POST",
                   headers:{"X-CSRFToken":$.cookie('csrftoken')},
                   data:{
                       dt:JSON.stringify(data_list)
                   },
                   success:function (data) {
                     if (JSON.parse(data)){
                         location.href='/'
                     }
                   }
               })
            })

        });
    </script>

{% endblock js%}

templates/questions.html
{% extends "index.html" %}
{% block content %}
    <div style="margin-left: 700px;margin-top: 20px;margin-bottom: 10px"><button class="btn btn-success" id="add">添加</button>
    <button class="btn btn-info ">完成</button></div>
    {% if question_list %}
        {% for question in question_list %}
            <div class="jumbotron">
             <span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"></span>
                <h4>问题：</h4>
                <p><textarea name="" id="" cols="50">{{ question.name }}</textarea></p>
                类型：<select name="" id="" style="height: 30px">
                            {% for type in type_list %}
                                {% if question.type == type.0 %}
                                    <option id={{ type.0 }} value="{{ type.0 }}" selected>{{ type.1 }}</option>
                                    {% else %}
                                    <option id={{ type.0 }} value="{{ type.0 }}">{{ type.1 }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                {% if question.type == 1 %}
                    <span>
                    <button class="btn btn-default option" style="margin-left: 80px">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>添加选项
                    </button>
                    {% for option in option_list %}
                        <li style="margin-top: 10px"><span>内容：</span><input type="text" value="{{ option.name }}"><span>分值：</span><input type="text" value="{{ option.score }}"> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></li>
                    {% endfor %}
                    </span>
                {% else %}
                    <span></span>
                {% endif %}
    </div>

        {% endfor %}

    {% else %}
        <div class="jumbotron">
        <h4>问题：</h4><p><textarea name="" id="" cols="50"></textarea></p>
        类型：<select name="" id="" style="height: 30px">
                            <option id="1" value="1">单选</option>
                            <option id="2" value="2">打分(1~10分)</option>
                            <option id="3" value="3">建议</option>
                </select>
            <span>
            <button class="btn btn-default option" style="margin-left: 80px">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>添加选项</button></span>
    </div>
    {% endif %}


{% endblock %}

{% block js %}
    <script>
    $(function () {
        $("#add").click(function () {
            var s = '<div class="jumbotron"> <span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"></span><h4>问题：</h4><p><textarea name="" id="" cols="50"></textarea></p>类型：<select name="" id="" style="height: 30px"> <option id="1" value="1">单选</option> <option id="2" value="3">打分(1~10分)</option> <option id="3" value="3">建议</option></select> <span> <button class="btn btn-default option" style="margin-left: 80px"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>添加选项</button></span></div>'
            $(".content").append(s)
        })
    });
    $(".content").on("change","select",function () {
        if ($(this).val()==="1"){
            var s='<button class="btn btn-default option" style="margin-left: 80px"><span class="glyphicon glyphicon-plus " aria-hidden="true"></span>添加选项</button>'
            $(this).next().append(s)
        }else{
            $(this).next("span").empty()
        }
    })
    $(".content").on("click",".option",function () {
        var s ='<li style="margin-top: 10px"><span>内容：</span><input type="text"><span>分值：</span><input type="text"> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></li>'
        $(this).parent().append(s)
    })


    </script>
{% endblock %}